language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.8
      - g++-5
      - valgrind

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8"; fi

script: 
  - cmake -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" .
  - make
  - valgrind --leak-check=full --track-origins=yes testsuite/cpp-sort-testsuite

notifications:
  email: false
